### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by scotthardwick** [fabiospampinato/vscode-commands#1]
Thanks for this cool extension!

Is there a command that can be put in the settings block of vscode-commands to engage Undo and Redo so that I can put those on the command bar?  I can't seem to locate them.

Thanks!

**Comment by fabiospampinato** [comment]
Have you tried `undo` and `redo`?

You can see a list of all commands provided by Code by opening the keyboard shortcuts file.

**Comment by scotthardwick** [comment]
Yikes. I feel dumb.

I was looking for something more complex and multileveled like the new file command... workbench.action.files.newUntitledFile so I didn't even think to try something as simple as one word undo and redo, which do indeed work.

Thanks for the help Fabio!
Best

**Comment by fabiospampinato** [comment]
No problem :)
