### ISSUE TITLE
Run arbitrary commands?

### ISSUE THREAD

**Issue by borekb** [fabiospampinato/vscode-commands#12]
I'd like to implement an "advanced switch to `master`" command that would basically do this:

```
git checkout master && yarn install
```

So it's not calling any built-in VSCode command but rather executing an arbitrary CLI command on my computer. Is that possible?

**Comment by fabiospampinato** [comment]
Yeah you can use the built-in `workbench.action.terminal.sendSequence` command for sending an arbitrary command to the terminal. I don't remember exactly how it works though, so you should look that up for yourself.

**Comment by borekb** [comment]
I'm trying this but it doesn't do anything:

```
{
  "commands": [
    {
      "command": "workbench.action.terminal.sendSequence",
      "arguments": ["git checkout master"],
      "text": "Checkout to master",
      "tooltip": "Test",
      "color": "#FFCC00"
    }
  ]
}
```

The [example in VSCode's docs](https://code.visualstudio.com/docs/editor/integrated-terminal#_send-text-from-a-keybinding) about keybinding uses a nested "text" argument like this:

```
{
  "key": "ctrl+u",
  "command": "workbench.action.terminal.sendSequence",
  "args": { "text": "\u001b[1;5D\u007f" }
}
```

Is that possible to specify with the Commands extension?

**Comment by fabiospampinato** [comment]
> Is that possible to specify with the Commands extension?

I don't actually know, try using this:

```
"arguments": [{ "text": "\u001b[1;5D\u007f" }],
```

**Comment by borekb** [comment]
That works! Is there a way to run this "behind the scenes" so that characters are not actually sent to my VSCode terminal?

Many questions, sorry :)

**Comment by fabiospampinato** [comment]
If you don't want to use terminals for this you'll have to define a vs code command that does that action yourself, basically you'll have to write a vs code extension for this.

If instead you just don't want the terminal to be opened/focused (as I think that's the default case) can define that command in [Terminals Manager](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-terminals) and then call it through it, check [this section](https://github.com/fabiospampinato/vscode-commands#plays-well-with-others) of the readme (scroll down a bit).

**Comment by borekb** [comment]
I'm actually trying to use your extension to avoid writing my own :) All I need is to execute two commands after I click some button somewhere and Commands is pretty close to be able to do that, but not entirely.

Thanks for taking time to answer my questions, I really appreciate it!

**Comment by fabiospampinato** [comment]
No problem! If there's already another extension for executing arbitrary commands in the background then maybe you could use that one in combination with this one.

**Comment by borekb** [comment]
I'm looking at [this](https://github.com/egodigital/vscode-powertools/wiki/Buttons) right now. Might be what I'm looking for.
