### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by mmoncalvo** [fabiospampinato/vscode-commands#15]
- Issue Type: `Performance`
- Extension Name: `vscode-commands`
- Extension Version: `1.2.5`
- OS Version: `Darwin x64 15.6.0`
- VSCode version: `1.36.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/Marco/fabiospampinato.vscode-commands-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by fabiospampinato** [comment]
Nothing useful in here. 

> ⚠️ Make sure to attach this file from your home-directory:

Where is it?

Also knowing your configuration would be useful.
