### ISSUE TITLE
How about moving configuration into user settings

### ISSUE THREAD

**Issue by neilsustc** [fabiospampinato/vscode-commands#2]
It will be better to put the configurations into the vscode user `settings.json`

**Comment by fabiospampinato** [comment]
I think you can already do this if you want, have you tried it?

**Comment by neilsustc** [comment]
Oh, I didn't realize that!
Thanks very much! I really appreciate your extension**s** (such as recently published Highlight)

**Comment by fabiospampinato** [comment]
I'm glad to hear that 😄
