### ISSUE TITLE
Filter by files in workspace 

### ISSUE THREAD

**Issue by ctf0** [fabiospampinato/vscode-commands#21]
is that possible ? for example if there is a `package.json` file in the project root folder, then show the item **x** & if not then hide it

ref: 
- https://code.visualstudio.com/api/references/vscode-api#workspace 
- https://code.visualstudio.com/api/references/vscode-api#Uri

**Comment by fabiospampinato** [comment]
Not possible currently. PR welcome for adding a `filterWorskspaceFileRegex` option 👍

**Comment by ctf0** [comment]
hi again, i will start working on this feature today, could u tell me where should the check be added in the ext logic ?
