### ISSUE TITLE
Using editor.action.insertSnippet with arguments

### ISSUE THREAD

**Issue by Schwarzarbeiter** [fabiospampinato/vscode-commands#22]
Hi,

i am using your extension and am quite happy with it. Unfortunatly, I can't figure out a way to use it with the inbuilt editor.action.insertSnippet command.

I want to add buttons which insert certain snippets, I tried this three approaches:

```
            "alignment": "left",
            "priority": -9996,
            "text": "$(file-media)",
            "tooltip": "Insert image reference",
            "command": "editor.action.insertSnippet",
            "arguments": ["![Subtitle...][imageID...:fig]"],
            "filterLanguageRegex": "markdown"
```
```
            "alignment": "left",
            "priority": -9995,
            "text": "$(file-add)",
            "tooltip": "Insert image import",
            "command": "editor.action.insertSnippet",
            "arguments": ["markdown", "MDX Image Import"],
            "filterLanguageRegex": "markdown"
```
```
            "alignment": "left",
            "priority": -9996,
            "text": "$(file-media)",
            "tooltip": "Insert image reference",
            "command": "editor.action.insertSnippet",
            "arguments": {
                  "snippet": "![Subtitle...][imageID...:fig]"
             },
            "filterLanguageRegex": "markdown"
```

While the first two just let the user manually choose a snippet instead of adding one directly, the third ends with an error. Thanks for your help.

**Comment by fabiospampinato** [comment]
Like, I don't know what kind of arguments `editor.action.insertSnippet` is expecting here.

**Comment by Schwarzarbeiter** [comment]
Thank you for the fast response. I do have the same issues with other actions as well. I want to provide arguments in the form of 
````
"arguments": {
  "key": "value"
}
````
This does not seem to be possible since i get the error: `Running the contributed command: 'editor.action.insertSnippet{"key":"value"}' failed.`. I get the same error with other extensions as well. My guess is that the argument parsing does not support this kind of arguments.

**Comment by Schwarzarbeiter** [comment]
I think it is an parsing problem, 
````
"arguments": {
  "key": "value"
}
```` 
should be executed as `editor.action.insertSnippet{key: "value"}` and not as `editor.action.insertSnippet{"key":"value"}`

**Comment by Schwarzarbeiter** [comment]
For future reference if someone runs into the same problem: 

The `commands` extension expects an array of commands, the 'insertSnippet` command expects an object with the "snippet" key. The correct syntax is:

````
{
  "alignment": "left",
  "priority": -9996,
  "text": "$(file-media)",
  "tooltip": "Insert image reference",
  "command": "editor.action.insertSnippet",
  "arguments":[{
    "snippet": "[Text](URL)$0"
  }],
  "filterLanguageRegex": "markdown"
}
