### ISSUE TITLE
Please add this to package.json to allow extension to run on remote connection

### ISSUE THREAD

**Issue by JtMotoX** [fabiospampinato/vscode-commands#25]
When connecting to a remote host by using Remote SSH extension, this extension is not loaded and must be installed on the remote host.  I have provided the fix below which I have tested on my local system.

https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location

Please add the following to the [package.json](https://github.com/fabiospampinato/vscode-commands/blob/master/package.json):
`"extensionKind": ["ui", "workspace"],`

**Comment by ajs256** [comment]
I've just opened a PR that should fix this - #29.
