### ISSUE TITLE
Unable to open 'commands.json': File is a directory.

### ISSUE THREAD

**Issue by gremo** [fabiospampinato/vscode-commands#27]
Anyone experiencing the same issue?

![Cattura](https://user-images.githubusercontent.com/1532616/83775328-15842900-a687-11ea-8218-4c502b10c030.PNG)

Actually `command.json` exists, and commands work.

**Comment by fabiospampinato** [comment]
When is that error triggered? Do you have to trigger any command in particular to make it show up?

**Comment by gremo** [comment]
Sorry, forgot to say it: just with "Commands: edit configuration". Of course I can edit `commands.json` by myself... just to make you know that on a clean install, VS Code latest version, it throws.

**Comment by Escalion86** [comment]
> Sorry, forgot to say it: just with "Commands: edit configuration". Of course I can edit `commands.json` by myself... just to make you know that on a clean install, VS Code latest version, it throws.

I have this error too!

**Comment by lujomu** [comment]
I had this error too right after installing the extension. However, after restarting VSCode once, the message did not return and the extension works fine.

**Comment by molejar** [comment]
I have same error only with new version of VS Code 1.50 and Windows 10 (User Installer). The extension is also not working with remote workspace (from Windows OS to Linux OS via remote SSH extension).  If both OS are Linux, then all is working as have.

**Comment by eseiler** [comment]
Im using this extension with WSL2 and the `commands.json` is created on the windows hardrive instead within the virtual machine.

Let's say the path to `commands.json` should be `/home/user/project/.vscode/commands.json` (in my VM).
But actually a file at `C:\home\user\project\.vscode\commands.json` (on the host machine) is created.
I guess it will use whatever drive vscode is installed on.

I'm also getting the `File is a directory` error when trying to edit the json via the command palette.
The `commands.json` on the host machine is actually used and editing the file results in changes in VScode on the VM.

**Comment by da-mask** [comment]
It took me a while to work out that this extension wouldn't work in a WSL2 container project. I've put my commands in the global `commands.commands` of settings.json.

**Comment by fabiospampinato** [comment]
This should be fixed in v2 of the extension. If it isn't please say so, ideally posting the new error emssage.
