### ISSUE TITLE
Correct icon-set

### ISSUE THREAD

**Issue by john-hillert** [fabiospampinato/vscode-commands#33]
The documentation (see image) provides a link to [octicons](https://primer.style/octicons/), but I have found that only half of the names for those icons work.  On the other hand, [these](https://code.visualstudio.com/api/references/icons-in-labels) seems to work.  Which document set is compatible?  Thanks.

![documentation_discussing_icons](https://user-images.githubusercontent.com/61890389/95898475-b8933080-0d54-11eb-8b8a-844f9d075f5f.png)

**Comment by fabiospampinato** [comment]
The correct icon set depends on which version of VS Code you are using. Basically octicons are the old set and codicons are the new set, I'll update the link but I'll have to update it across all my extensions so it may take a bit.

**Comment by bigbadmoshe** [comment]
These are working for me
https://microsoft.github.io/vscode-codicons/dist/codicon.html

**Comment by fabiospampinato** [comment]
Fixed in v2 of the extension.
