### ISSUE TITLE
[Feature Request] Run external command directly

### ISSUE THREAD

**Issue by lonix1** [fabiospampinato/vscode-commands#37]
It would be nice to be able to run an external command, like so:

Linux:
````json
"command": "gnome-terminal --working-directory=$(pwd)/src/Foo/ --quiet --command 'ls -lah'",
````
Windows:
````json
"command": "cmd ...etc.",
````

That opens the command directly, without going through the built-in terminal, or a companion extension.

As you can see in [this extension](https://marketplace.visualstudio.com/items?itemName=gsppvo.vscode-commandbar), it's possible - but that extension is abandonware.

Would be nice to have that functionality in this extension. Thanks!

**Comment by fabiospampinato** [comment]
This feels out of scope, I have another extension which if it's not buggy supports running arbitrary commands https://github.com/fabiospampinato/vscode-terminals

You'd have to wire the two extensions to have that working like you want. If my other extension is broken in any case executing a shell command should be handled by some other extension, this extension's job is to trigger commands, providing a command for executing shell scripts is out of scope.
