### ISSUE TITLE
Arrow Switch $(arrow-switch) not displaying even after refresh

### ISSUE THREAD

**Issue by ondrovic** [fabiospampinato/vscode-commands#39]
Trying to use the [arrow-switch](https://primer.style/octicons/arrow-switch-24)

Env:

Ubuntu 20.04
vscode: 1.62.3
Commands: v1.4.3

```
"text": "$(arrow-switch)",
"tooltip": "Make Migration",
"color": "#FFFF"
```
![arrow-icon](https://user-images.githubusercontent.com/3682042/143084497-b5dd6321-6bd1-4cb9-abf8-24abc61cf99d.png)

**Comment by bigbadmoshe** [comment]
These are working for me
https://microsoft.github.io/vscode-codicons/dist/codicon.html
