### ISSUE TITLE
Support for running inside containers

### ISSUE THREAD

**Issue by akaibukai** [fabiospampinato/vscode-commands#41]
Hello,

In a way to circumvent the following [issue (allowing shortcuts)](https://github.com/fabiospampinato/vscode-terminals/issues/65) of Terminals Manager (BTW thank you for all your work)..

I discovered that plugin.

However it simply doesn't work when using VS Code Remote Containers feature (aka devcontainer).

I don't know why it's not possible to install it inside remote containers but is it possible to make it work?

Thank you very much.

**Comment by fabiospampinato** [comment]
I think extensions have to explicitly say that they support remote containers or something, I should look into this, I'm not familiar with how this works.

**Comment by fabiospampinato** [comment]
Closing as duplicate of #35
