### ISSUE TITLE
Publish to open-vsx.org

### ISSUE THREAD

**Issue by femto-code** [fabiospampinato/vscode-commands#42]
Please publish the extension on [open-vsx.org](https://open-vsx.org/). Thank you.

**Comment by femto-code** [comment]
Out of curiosity, why don't you have the interest for open-vsx - allowing more users to access your extension?

There are not few people using VSCodium with open-vsx as extension backend as a result of MSs telemetry crap (in VS Code).

**Comment by fabiospampinato** [comment]
I just don't use it, I already have more than enough stuff to deal with, I don't want to think about one extra thing I don't even need.

There may be better options other than requiring extensions author to publish things multiple times, maybe they could interface directly with MS' marketplace? Maybe that could be scraped? I don't know.
