### ISSUE TITLE
Failed to open configuration file in Windows

### ISSUE THREAD

**Issue by joaomoreno** [fabiospampinato/vscode-commands#44]
Steps:

1. Run `Commands: Edit Configuration`

🐛 Error opening the file

![image](https://user-images.githubusercontent.com/22350/212275907-74f64422-0bf4-4233-9f85-473c38296d2a.png)

**Comment by fabiospampinato** [comment]
I need to check why that's failing under Windows.

In the meantime you can define your commands under `"commands.commands"` in vscode's settings file.

**Comment by alexravenna** [comment]
I get this same error.

**Comment by fabiospampinato** [comment]
This should be fixed in v2 of the extension. If it isn't please say so, ideally posting the new error message.

**Comment by alexravenna** [comment]
Yes, the command now works properly! Thank you 😃 .
