### ISSUE TITLE
toggle between settings

### ISSUE THREAD

**Issue by hansu** [fabiospampinato/vscode-commands#46]
Is it possible to define a button which toggles between assigning two values to a setting and maybe change the icon according to the current setting?

I have in mind e.g. toggling between those two settings:

"workbench.editor.navigationScope": "editor"

and

"workbench.editor.navigationScope": "global"

**Comment by fabiospampinato** [comment]
Not with this extension, you'd need another extension that can actually toggle between blocks of settings, then that could be wired with this extension to add a button for it in the statusbar.

I consider this out of scope for this extension, but it's a cool idea.

**Comment by hansu** [comment]
Okay thanks for your quick feedback. However, really nice extension, I like it 👍
