### ISSUE TITLE
Icons not found

### ISSUE THREAD

**Issue by serhumanos** [fabiospampinato/vscode-commands#47]
Icons from the reference: https://octicons.github.com/ are not found
and some of the icons look different
for example icon "columns"

**Comment by whoisjim** [comment]
I noticed this issue as well,

It does look like you can use all of the vs code icons though, they are all listed here [https://code.visualstudio.com/api/references/icons-in-labels](https://code.visualstudio.com/api/references/icons-in-labels)

Maybe the two icon sets used to be the same but after 6 years they drifted apart.

**Comment by serhumanos** [comment]
> I noticed this issue as well,
> 
> It does look like you can use all of the vs code icons though, they are all listed here https://code.visualstudio.com/api/references/icons-in-labels
> 
> Maybe the two icon sets used to be the same but after 6 years they drifted apart.

That works great, The icons pack you reference is works as expected
thanks!

**Comment by fabiospampinato** [comment]
Fixed in v2 of the extension.
