### ISSUE TITLE
how to send command like 'ls' to the terminal

### ISSUE THREAD

**Issue by leetbox** [fabiospampinato/vscode-commands#6]
Hi, I'm new to vscode and I really dont understand how I can run some basic terminal command like 'ls' by using your plugin. Is it possible? If yes, can you show me one example? Thanks.

**Comment by fabiospampinato** [comment]
Hi, it's definitely possible. There are 2 ways of doing this that I'm aware of:

1. VSC provides the `workbench.action.terminal.sendSequence` command for sending some text to a terminal, you could use it with a configuration like this:

```json
{
  "commands": [
    {
      "alignment": "right",
      "command": "workbench.action.terminal.sendSequence",
      "arguments": [{ "text": "ls\n" }],
      "text": "ls",
      "color": "#FFCC00"
    }
  ]
}
```

2. If you need more advanced stuff, like spawning a new terminal etc. you'll have to first define that terminal using [Terminals Manager](https://github.com/fabiospampinato/vscode-terminals) and then execute it using the `terminals.runTerminalByName` command, so the configuration will look like this:

```json
{
  "commands": [
    {
      "text": "Init",
      "command": "terminals.runTerminalByName",
      "arguments": ["init"],
      "tooltip": "Init the project"
    }
  ]
}
```
