### ISSUE TITLE
Add a schema for commands.commands setting to that vscode offers autocompletion

### ISSUE THREAD

**Issue by hediet** [fabiospampinato/vscode-commands#9]
For example, gitlens has support for autocompletion in the json settings editor:
![image](https://user-images.githubusercontent.com/2931520/52567695-30d18200-2e0d-11e9-8734-2595c29ff72d.png)

Whereas commands doesn't:
![image](https://user-images.githubusercontent.com/2931520/52567756-52326e00-2e0d-11e9-8cfa-815d0bf824f5.png)

Gitlense is achieving this by adding a schema:
https://github.com/eamodio/vscode-gitlens/blob/master/package.json#L1637

**Comment by fabiospampinato** [comment]
GitLense is setting a schema for its settings defined in the default settings file, but we also support setting settings on a separate `.vscode/bump.json`, I'm not sure how we could provide autocompletion for that.
